### ISSUE TITLE
Readability of the diagram in efficient logging

### ISSUE THREAD

**Issue by qrilka** [AntoniosBarotsis/antoniosbarotsis.github.io#3]
Hi, in your post you say
> I ended up creating a ✨technical diagram✨ to convey the overall picture better than my writing could.

While the diagram is clearly helpful you could improve it by making labels readable, e.g. that's what I see in my browser:
![diag](https://github.com/user-attachments/assets/a3388231-c76a-4470-a247-23f40923d1bd)

And I needed to zoom in to understand e.g. that the rectangle on the right contains "Main" as its label.

P.S. Thanks for the post

**Comment by AntoniosBarotsis** [comment]
Thanks for the issue!

I mostly tested this on my laptop with dark mode where it looked fine but I couldn't for the life of me figure out how to make this look better on mobile (and I completely forgot to test in light mode). 

I'll see if i can add outlines to make it look better.

**Comment by AntoniosBarotsis** [comment]
Should be better now! [Added a filter that inverts SVGs in dark mode](https://github.com/AntoniosBarotsis/antoniosbarotsis.github.io/commit/b092e1aca0939a33c8f089ae7f14f50f39cc8c82). Might need a cache clear for the changes to appear properly but it should be live now. 

If anything is still off feel free to reopen this/make a new one :)

![image](https://github.com/user-attachments/assets/8cbf9505-926d-4206-8223-75116ad46312)
![image](https://github.com/user-attachments/assets/949484ab-38e9-4f14-a469-eb38a8bb0d4e)
